window.EXERCISES = [
  { name: "Barbell Back Squat", muscles: ["quads", "glutes", "core"], equipment: "barbell", compound: true },
  { name: "Front Squat", muscles: ["quads", "core"], equipment: "barbell", compound: true },
  { name: "Romanian Deadlift", muscles: ["hamstrings", "glutes", "back"], equipment: "barbell", compound: true },
  { name: "Conventional Deadlift", muscles: ["hamstrings", "glutes", "back", "core"], equipment: "barbell", compound: true },
  { name: "Barbell Bench Press", muscles: ["chest", "triceps", "shoulders"], equipment: "barbell", compound: true },
  { name: "Incline Barbell Press", muscles: ["chest", "shoulders", "triceps"], equipment: "barbell", compound: true },
  { name: "Overhead Press", muscles: ["shoulders", "triceps", "core"], equipment: "barbell", compound: true },
  { name: "Pendlay Row", muscles: ["back", "biceps", "core"], equipment: "barbell", compound: true },
  { name: "Bulgarian Split Squat", muscles: ["quads", "glutes"], equipment: "dumbbell", compound: true },
  { name: "Dumbbell Walking Lunge", muscles: ["quads", "glutes", "hamstrings"], equipment: "dumbbell", compound: true },
  { name: "Dumbbell Flat Press", muscles: ["chest", "triceps", "shoulders"], equipment: "dumbbell", compound: true },
  { name: "Dumbbell Incline Press", muscles: ["chest", "shoulders", "triceps"], equipment: "dumbbell", compound: true },
  { name: "Single-Arm Dumbbell Row", muscles: ["back", "biceps"], equipment: "dumbbell", compound: true },
  { name: "Dumbbell Lateral Raise", muscles: ["shoulders"], equipment: "dumbbell", compound: false },
  { name: "Dumbbell Rear Delt Fly", muscles: ["shoulders", "back"], equipment: "dumbbell", compound: false },
  { name: "Hammer Curl", muscles: ["biceps"], equipment: "dumbbell", compound: false },
  { name: "Dumbbell Skull Crusher", muscles: ["triceps"], equipment: "dumbbell", compound: false },
  { name: "Goblet Squat", muscles: ["quads", "glutes", "core"], equipment: "kettlebell", compound: true },
  { name: "Kettlebell Swing", muscles: ["hamstrings", "glutes", "core"], equipment: "kettlebell", compound: true },
  { name: "Kettlebell Clean and Press", muscles: ["shoulders", "core", "quads"], equipment: "kettlebell", compound: true },
  { name: "Cable Chest Fly", muscles: ["chest"], equipment: "cable", compound: false },
  { name: "Cable Low Row", muscles: ["back", "biceps"], equipment: "cable", compound: true },
  { name: "Lat Pulldown", muscles: ["back", "biceps"], equipment: "cable", compound: true },
  { name: "Cable Face Pull", muscles: ["shoulders", "back"], equipment: "cable", compound: false },
  { name: "Cable Triceps Pushdown", muscles: ["triceps"], equipment: "cable", compound: false },
  { name: "Cable Overhead Triceps Extension", muscles: ["triceps"], equipment: "cable", compound: false },
  { name: "Cable Biceps Curl", muscles: ["biceps"], equipment: "cable", compound: false },
  { name: "Cable Woodchop", muscles: ["core"], equipment: "cable", compound: false },
  { name: "Leg Press", muscles: ["quads", "glutes"], equipment: "machine", compound: true },
  { name: "Hack Squat", muscles: ["quads", "glutes"], equipment: "machine", compound: true },
  { name: "Leg Extension", muscles: ["quads"], equipment: "machine", compound: false },
  { name: "Seated Hamstring Curl", muscles: ["hamstrings"], equipment: "machine", compound: false },
  { name: "Glute Drive Machine", muscles: ["glutes"], equipment: "machine", compound: true },
  { name: "Chest Press Machine", muscles: ["chest", "triceps"], equipment: "machine", compound: true },
  { name: "Pec Deck", muscles: ["chest"], equipment: "machine", compound: false },
  { name: "Machine Shoulder Press", muscles: ["shoulders", "triceps"], equipment: "machine", compound: true },
  { name: "Seated Row Machine", muscles: ["back", "biceps"], equipment: "machine", compound: true },
  { name: "Assisted Pull-Up", muscles: ["back", "biceps"], equipment: "machine", compound: true },
  { name: "Standing Calf Raise", muscles: ["calves"], equipment: "machine", compound: false },
  { name: "Smith Machine Split Squat", muscles: ["quads", "glutes"], equipment: "smith-machine", compound: true },
  { name: "Smith Machine Bench Press", muscles: ["chest", "triceps", "shoulders"], equipment: "smith-machine", compound: true },
  { name: "Smith Machine RDL", muscles: ["hamstrings", "glutes"], equipment: "smith-machine", compound: true },
  { name: "Pull-Up", muscles: ["back", "biceps", "core"], equipment: "bodyweight", compound: true },
  { name: "Dip", muscles: ["chest", "triceps", "shoulders"], equipment: "bodyweight", compound: true },
  { name: "Push-Up", muscles: ["chest", "triceps", "core"], equipment: "bodyweight", compound: true },
  { name: "Pike Push-Up", muscles: ["shoulders", "triceps"], equipment: "bodyweight", compound: true },
  { name: "Walking Lunge", muscles: ["quads", "glutes"], equipment: "bodyweight", compound: true },
  { name: "Single-Leg Hip Bridge", muscles: ["glutes", "hamstrings", "core"], equipment: "bodyweight", compound: false },
  { name: "Hanging Knee Raise", muscles: ["core"], equipment: "bodyweight", compound: false },
  { name: "Side Plank", muscles: ["core"], equipment: "bodyweight", compound: false },
  { name: "EZ Bar Curl", muscles: ["biceps"], equipment: "ez-bar", compound: false },
  { name: "EZ Bar Skull Crusher", muscles: ["triceps"], equipment: "ez-bar", compound: false },
  { name: "Barbell Hip Thrust", muscles: ["glutes", "hamstrings", "core"], equipment: "barbell", compound: true },
  { name: "Seated Dumbbell Shoulder Press", muscles: ["shoulders", "triceps"], equipment: "dumbbell", compound: true },
  { name: "Incline Dumbbell Curl", muscles: ["biceps"], equipment: "dumbbell", compound: false },
  { name: "Cable Lateral Raise", muscles: ["shoulders"], equipment: "cable", compound: false },
  { name: "Chest-Supported Row", muscles: ["back", "biceps"], equipment: "dumbbell", compound: true },
  { name: "Machine Ab Crunch", muscles: ["core"], equipment: "machine", compound: false },
  { name: "Standing Soleus Raise", muscles: ["calves"], equipment: "machine", compound: false },
  { name: "Sled Push", muscles: ["quads", "glutes", "core"], equipment: "sled", compound: true },
  { name: "Sled Backward Drag", muscles: ["quads", "calves"], equipment: "sled", compound: true },
  { name: "Landmine Press", muscles: ["chest", "shoulders", "triceps"], equipment: "landmine", compound: true },
  { name: "Landmine Row", muscles: ["back", "biceps", "core"], equipment: "landmine", compound: true }
];
